defaults: &defaults
  docker:
    - image: circleci/openjdk:10-jdk-node

  working_directory: ~/docker-mvn-chrome

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Image
          command: |
            docker build -t kdbuck/mvn-chrome .
            docker tag kdbuck/mvn-chrome:latest kdbuck/mvn-chrome:${CIRCLE_SHA1}
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push kdbuck/mvn-chrome:latest
            docker logout

  release:
    <<: *defaults

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Release Image
          command: |
            docker build -t kdbuck/mvn-chrome:${CIRCLE_TAG} .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push kdbuck/mvn-chrome:${CIRCLE_TAG}
            docker logout

workflows:
  version: 2

  build-and-push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - master

  build-and-release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
